receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4318 # Port for aggregated metrics

processors:
  streamingaggregation:
    window_size: 30s # Aggregate over 30-second windows
    max_memory_mb: 100 # Memory limit
    stale_data_threshold: 2m # Reset cumulative state after 2 minutes of no data

  metricstransform:
    transforms:
      - include: ".*"
        match_type: regexp
        action: update
        new_name: "aggregated_$$0"

exporters:
  otlphttp:
    endpoint: http://prometheus:9090/api/v1/otlp
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [streamingaggregation, metricstransform]
      exporters: [otlphttp]

  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
